"""업종별 컬러/폰트/스타일/효과 프리셋 정의"""

CATEGORY_TEMPLATES = {
    "음식점": {
        "primary": (220, 50, 50),
        "secondary": (255, 255, 255),
        "accent": (255, 200, 50),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "gradient_bottom",
        "badge_style": "rounded",
        "badge_bg": (220, 50, 50),
        "badge_text": (255, 255, 255),
        "panel_bg": (255, 255, 255),
        "panel_text": (50, 50, 50),
        "fonts": {
            "display": "DoHyeon-Regular.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "Jua-Regular.ttf",
            "handwriting": "SingleDay-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "classic",
        "decoration_color": (255, 200, 50),
        "text_effects": {
            "headline": {"effect": "outline", "params": {"stroke_width": 4, "stroke_color": (0, 0, 0)}},
            "subtext": {"effect": "bg_box", "params": {"bg_color": (0, 0, 0), "bg_alpha": 140, "radius": 12, "padding": 16}},
            "brand_name": {"effect": "shadow", "params": {"offset_x": 2, "offset_y": 2, "shadow_alpha": 120}},
            "accent": {"effect": "underline_accent", "params": {"bar_color": (255, 200, 50)}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (220, 50, 50), "bg_alpha": 220}},
        },
    },
    "헬스": {
        "primary": (30, 30, 30),
        "secondary": (220, 50, 50),
        "accent": (255, 255, 100),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "dark_overlay",
        "badge_style": "pill",
        "badge_bg": (220, 50, 50),
        "badge_text": (255, 255, 255),
        "panel_bg": (30, 30, 30),
        "panel_text": (255, 255, 255),
        "fonts": {
            "display": "BlackHanSans-Regular.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "Gasoek-One.ttf",
            "handwriting": "Jua-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "brand_bar",
        "decoration_color": (255, 255, 100),
        "text_effects": {
            "headline": {"effect": "glow", "params": {"glow_color": (255, 50, 50), "glow_radius": 5}},
            "subtext": {"effect": "outline", "params": {"stroke_width": 3, "stroke_color": (0, 0, 0)}},
            "brand_name": {"effect": "neon", "params": {"neon_color": (255, 50, 50)}},
            "accent": {"effect": "shadow_3d", "params": {"depth": 5}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (220, 50, 50), "bg_alpha": 240}},
        },
    },
    "뷰티": {
        "primary": (200, 170, 140),
        "secondary": (100, 70, 50),
        "accent": (0, 180, 180),
        "text_on_primary": (60, 40, 20),
        "text_on_content": (255, 255, 255),
        "overlay": "soft_vignette",
        "badge_style": "rounded",
        "badge_bg": (0, 180, 180),
        "badge_text": (255, 255, 255),
        "panel_bg": (250, 245, 238),
        "panel_text": (80, 60, 40),
        "fonts": {
            "display": "Pretendard-Black.otf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "Jua-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "centered",
        "decoration_color": (0, 180, 180),
        "text_effects": {
            "headline": {"effect": "shadow", "params": {"offset_x": 4, "offset_y": 4, "shadow_alpha": 160}},
            "subtext": {"effect": "highlight", "params": {"highlight_color": (0, 180, 180), "highlight_alpha": 180}},
            "brand_name": {"effect": "none", "params": {}},
            "accent": {"effect": "underline_accent", "params": {"bar_color": (0, 180, 180)}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (0, 180, 180), "bg_alpha": 200}},
        },
    },
    "학원": {
        "primary": (50, 150, 80),
        "secondary": (255, 255, 255),
        "accent": (255, 165, 0),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "gradient_bottom",
        "badge_style": "square",
        "badge_bg": (50, 150, 80),
        "badge_text": (255, 255, 255),
        "panel_bg": (245, 245, 245),
        "panel_text": (50, 50, 50),
        "fonts": {
            "display": "GmarketSansBold.otf",
            "headline": "Pretendard-Black.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "SingleDay-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "card_style",
        "decoration_color": (255, 165, 0),
        "text_effects": {
            "headline": {"effect": "bg_box", "params": {"bg_color": (50, 150, 80), "bg_alpha": 200, "radius": 8, "padding": 20}},
            "subtext": {"effect": "shadow", "params": {"offset_x": 3, "offset_y": 3, "shadow_alpha": 140}},
            "brand_name": {"effect": "outline", "params": {"stroke_width": 2, "stroke_color": (0, 0, 0)}},
            "accent": {"effect": "shadow_3d", "params": {"depth": 4}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (50, 150, 80), "bg_alpha": 220}},
        },
    },
    "병원": {
        "primary": (140, 100, 60),
        "secondary": (255, 245, 230),
        "accent": (200, 170, 100),
        "text_on_primary": (255, 245, 230),
        "text_on_content": (255, 255, 255),
        "overlay": "light_overlay",
        "badge_style": "rounded",
        "badge_bg": (140, 100, 60),
        "badge_text": (255, 245, 230),
        "panel_bg": (255, 250, 240),
        "panel_text": (80, 60, 40),
        "fonts": {
            "display": "Pretendard-Black.otf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "Jua-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "centered",
        "decoration_color": (200, 170, 100),
        "text_effects": {
            "headline": {"effect": "outline", "params": {"stroke_width": 3, "stroke_color": (80, 60, 30)}},
            "subtext": {"effect": "bg_box", "params": {"bg_color": (140, 100, 60), "bg_alpha": 180, "radius": 10, "padding": 14}},
            "brand_name": {"effect": "shadow", "params": {"offset_x": 2, "offset_y": 2, "shadow_alpha": 100}},
            "accent": {"effect": "underline_accent", "params": {"bar_color": (200, 170, 100)}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (140, 100, 60), "bg_alpha": 200}},
        },
    },
    "안경": {
        "primary": (230, 130, 30),
        "secondary": (30, 30, 30),
        "accent": (255, 255, 255),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "dark_overlay",
        "badge_style": "pill",
        "badge_bg": (255, 255, 255),
        "badge_text": (230, 130, 30),
        "panel_bg": (230, 130, 30),
        "panel_text": (255, 255, 255),
        "fonts": {
            "display": "Gasoek-One.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "Jua-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "brand_bar",
        "decoration_color": (255, 255, 255),
        "text_effects": {
            "headline": {"effect": "outline", "params": {"stroke_width": 4, "stroke_color": (0, 0, 0)}},
            "subtext": {"effect": "shadow", "params": {"offset_x": 3, "offset_y": 3, "shadow_alpha": 160}},
            "brand_name": {"effect": "double_outline", "params": {"outer_color": (0, 0, 0), "inner_color": (230, 130, 30)}},
            "accent": {"effect": "shadow_3d", "params": {"depth": 5}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (230, 130, 30), "bg_alpha": 240}},
        },
    },
    "부동산": {
        "primary": (44, 62, 107),
        "secondary": (255, 255, 255),
        "accent": (70, 130, 220),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "gradient_bottom",
        "badge_style": "rounded",
        "badge_bg": (44, 62, 107),
        "badge_text": (255, 255, 255),
        "panel_bg": (245, 248, 255),
        "panel_text": (44, 62, 107),
        "fonts": {
            "display": "Pretendard-Black.otf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "Jua-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "card_style",
        "decoration_color": (70, 130, 220),
        "text_effects": {
            "headline": {"effect": "outline", "params": {"stroke_width": 3, "stroke_color": (20, 30, 60)}},
            "subtext": {"effect": "bg_box", "params": {"bg_color": (44, 62, 107), "bg_alpha": 180, "radius": 10, "padding": 16}},
            "brand_name": {"effect": "shadow", "params": {"offset_x": 2, "offset_y": 2, "shadow_alpha": 120}},
            "accent": {"effect": "none", "params": {}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (44, 62, 107), "bg_alpha": 220}},
        },
    },
    "골프": {
        "primary": (26, 92, 42),
        "secondary": (212, 175, 55),
        "accent": (255, 255, 255),
        "text_on_primary": (212, 175, 55),
        "text_on_content": (255, 255, 255),
        "overlay": "dark_overlay",
        "badge_style": "pill",
        "badge_bg": (212, 175, 55),
        "badge_text": (26, 92, 42),
        "panel_bg": (26, 50, 30),
        "panel_text": (255, 255, 255),
        "fonts": {
            "display": "Gasoek-One.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "Dongle-Bold.ttf",
            "handwriting": "SingleDay-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "brand_bar",
        "decoration_color": (212, 175, 55),
        "text_effects": {
            "headline": {"effect": "outline", "params": {"stroke_width": 5, "stroke_color": (0, 0, 0)}},
            "subtext": {"effect": "shadow", "params": {"offset_x": 3, "offset_y": 3, "shadow_alpha": 160}},
            "brand_name": {"effect": "shadow", "params": {"offset_x": 3, "offset_y": 3, "shadow_alpha": 140}},
            "accent": {"effect": "underline_accent", "params": {"bar_color": (212, 175, 55)}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (26, 92, 42), "bg_alpha": 220}},
        },
    },
    "핸드폰": {
        "primary": (0, 102, 204),
        "secondary": (255, 255, 255),
        "accent": (0, 200, 255),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "gradient_bottom",
        "badge_style": "square",
        "badge_bg": (0, 102, 204),
        "badge_text": (255, 255, 255),
        "panel_bg": (240, 248, 255),
        "panel_text": (0, 70, 140),
        "fonts": {
            "display": "BlackHanSans-Regular.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "Jua-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "minimal",
        "decoration_color": (0, 200, 255),
        "text_effects": {
            "headline": {"effect": "glow", "params": {"glow_color": (0, 150, 255), "glow_radius": 4}},
            "subtext": {"effect": "outline", "params": {"stroke_width": 3, "stroke_color": (0, 0, 0)}},
            "brand_name": {"effect": "neon", "params": {"neon_color": (0, 150, 255)}},
            "accent": {"effect": "shadow_3d", "params": {"depth": 4}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (0, 102, 204), "bg_alpha": 230}},
        },
    },
    "동물병원": {
        "primary": (74, 173, 232),
        "secondary": (255, 255, 255),
        "accent": (255, 200, 100),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "gradient_bottom",
        "badge_style": "rounded",
        "badge_bg": (74, 173, 232),
        "badge_text": (255, 255, 255),
        "panel_bg": (240, 250, 255),
        "panel_text": (50, 100, 150),
        "fonts": {
            "display": "DoHyeon-Regular.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "Jua-Regular.ttf",
            "handwriting": "SingleDay-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "classic",
        "decoration_color": (255, 200, 100),
        "text_effects": {
            "headline": {"effect": "outline", "params": {"stroke_width": 3, "stroke_color": (0, 0, 0)}},
            "subtext": {"effect": "bg_box", "params": {"bg_color": (74, 173, 232), "bg_alpha": 160, "radius": 12, "padding": 14}},
            "brand_name": {"effect": "shadow", "params": {"offset_x": 2, "offset_y": 2, "shadow_alpha": 120}},
            "accent": {"effect": "underline_accent", "params": {"bar_color": (255, 200, 100)}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (74, 173, 232), "bg_alpha": 220}},
        },
    },
    "미용실": {
        "primary": (212, 97, 140),
        "secondary": (255, 255, 255),
        "accent": (255, 200, 220),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "soft_vignette",
        "badge_style": "pill",
        "badge_bg": (212, 97, 140),
        "badge_text": (255, 255, 255),
        "panel_bg": (255, 245, 248),
        "panel_text": (150, 50, 80),
        "fonts": {
            "display": "Pretendard-Black.otf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "Dongle-Bold.ttf",
            "handwriting": "SingleDay-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "centered",
        "decoration_color": (255, 200, 220),
        "text_effects": {
            "headline": {"effect": "shadow", "params": {"offset_x": 4, "offset_y": 4, "shadow_alpha": 160}},
            "subtext": {"effect": "highlight", "params": {"highlight_color": (212, 97, 140), "highlight_alpha": 160}},
            "brand_name": {"effect": "none", "params": {}},
            "accent": {"effect": "underline_accent", "params": {"bar_color": (212, 97, 140)}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (212, 97, 140), "bg_alpha": 220}},
        },
    },
    "기타": {
        "primary": (74, 74, 74),
        "secondary": (255, 255, 255),
        "accent": (100, 180, 255),
        "text_on_primary": (255, 255, 255),
        "text_on_content": (255, 255, 255),
        "overlay": "gradient_bottom",
        "badge_style": "rounded",
        "badge_bg": (74, 74, 74),
        "badge_text": (255, 255, 255),
        "panel_bg": (245, 245, 245),
        "panel_text": (50, 50, 50),
        "fonts": {
            "display": "Gasoek-One.ttf",
            "headline": "GmarketSansBold.otf",
            "body": "Pretendard-Bold.otf",
            "accent": "DoHyeon-Regular.ttf",
            "handwriting": "SingleDay-Regular.ttf",
            "badge": "NanumSquareRoundEB.ttf",
        },
        "bar_style": "classic",
        "decoration_color": (100, 180, 255),
        "text_effects": {
            "headline": {"effect": "shadow", "params": {"offset_x": 3, "offset_y": 3, "shadow_alpha": 140}},
            "subtext": {"effect": "none", "params": {}},
            "brand_name": {"effect": "outline", "params": {"stroke_width": 2, "stroke_color": (0, 0, 0)}},
            "accent": {"effect": "shadow_3d", "params": {"depth": 4}},
            "cta_text": {"effect": "bg_pill", "params": {"bg_color": (74, 74, 74), "bg_alpha": 200}},
        },
    },
}


def hex_to_rgb(hex_str: str) -> tuple:
    """#RRGGBB → (R, G, B)"""
    hex_str = hex_str.lstrip("#")
    return tuple(int(hex_str[i:i+2], 16) for i in (0, 2, 4))


def get_template(category: str, primary_override: str = "",
                 secondary_override: str = "") -> dict:
    """카테고리별 템플릿 반환. 사용자 컬러로 오버라이드 가능."""
    tpl = CATEGORY_TEMPLATES.get(category, CATEGORY_TEMPLATES["기타"]).copy()
    if primary_override:
        tpl["primary"] = hex_to_rgb(primary_override)
    if secondary_override:
        tpl["secondary"] = hex_to_rgb(secondary_override)
    return tpl
